from . import heb_Addic7edProvider
from . import eng_Addic7edProvider
from . import rus_Addic7edProvider
from . import spa_Addic7edProvider
from . import tur_Addic7edProvider
from . import nor_Addic7edProvider
from . import slo_Addic7edProvider
from . import cze_Addic7edProvider
from . import bul_Addic7edProvider