# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SubiT_UI_Main.ui'
#
# Created: Sun Dec 18 22:48:53 2011
#      by: PyQt4 UI code generator 4.8.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_SubiTMainForm(object):
    def setupUi(self, SubiTMainForm):
        SubiTMainForm.setObjectName(_fromUtf8("SubiTMainForm"))
        SubiTMainForm.setWindowModality(QtCore.Qt.WindowModal)
        SubiTMainForm.setEnabled(True)
        SubiTMainForm.resize(710, 390)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(SubiTMainForm.sizePolicy().hasHeightForWidth())
        SubiTMainForm.setSizePolicy(sizePolicy)
        SubiTMainForm.setMinimumSize(QtCore.QSize(710, 390))
        SubiTMainForm.setMaximumSize(QtCore.QSize(710, 390))
        SubiTMainForm.setWindowTitle(QtGui.QApplication.translate("SubiTMainForm", "SubiT 1.1.0", None, QtGui.QApplication.UnicodeUTF8))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SubiTMainForm.setWindowIcon(icon)
        self.logGroupBox = QtGui.QGroupBox(SubiTMainForm)
        self.logGroupBox.setGeometry(QtCore.QRect(10, 0, 341, 131))
        self.logGroupBox.setTitle(QtGui.QApplication.translate("SubiTMainForm", " Log ", None, QtGui.QApplication.UnicodeUTF8))
        self.logGroupBox.setObjectName(_fromUtf8("logGroupBox"))
        self.textEdit = QtGui.QTextEdit(self.logGroupBox)
        self.textEdit.setGeometry(QtCore.QRect(5, 20, 331, 101))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        self.textEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.moviesGroupBox = QtGui.QGroupBox(SubiTMainForm)
        self.moviesGroupBox.setGeometry(QtCore.QRect(10, 130, 341, 201))
        self.moviesGroupBox.setTitle(QtGui.QApplication.translate("SubiTMainForm", " Movies ", None, QtGui.QApplication.UnicodeUTF8))
        self.moviesGroupBox.setObjectName(_fromUtf8("moviesGroupBox"))
        self.listWidget = QtGui.QListWidget(self.moviesGroupBox)
        self.listWidget.setGeometry(QtCore.QRect(10, 20, 321, 101))
        self.listWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        self.inputGoupBox = QtGui.QGroupBox(self.moviesGroupBox)
        self.inputGoupBox.setGeometry(QtCore.QRect(10, 120, 321, 81))
        self.inputGoupBox.setTitle(QtGui.QApplication.translate("SubiTMainForm", "Input ", None, QtGui.QApplication.UnicodeUTF8))
        self.inputGoupBox.setFlat(True)
        self.inputGoupBox.setObjectName(_fromUtf8("inputGoupBox"))
        self.lineEdit = QtGui.QLineEdit(self.inputGoupBox)
        self.lineEdit.setGeometry(QtCore.QRect(0, 20, 295, 21))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.browseBTN = QtGui.QToolButton(self.inputGoupBox)
        self.browseBTN.setGeometry(QtCore.QRect(295, 20, 25, 21))
        self.browseBTN.setText(QtGui.QApplication.translate("SubiTMainForm", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.browseBTN.setAutoRaise(False)
        self.browseBTN.setArrowType(QtCore.Qt.NoArrow)
        self.browseBTN.setObjectName(_fromUtf8("browseBTN"))
        self.goBTN = QtGui.QPushButton(self.inputGoupBox)
        self.goBTN.setGeometry(QtCore.QRect(0, 42, 321, 30))
        self.goBTN.setText(QtGui.QApplication.translate("SubiTMainForm", "Go", None, QtGui.QApplication.UnicodeUTF8))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("icon-go.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.goBTN.setIcon(icon1)
        self.goBTN.setIconSize(QtCore.QSize(24, 24))
        self.goBTN.setCheckable(False)
        self.goBTN.setAutoExclusive(False)
        self.goBTN.setAutoDefault(False)
        self.goBTN.setDefault(False)
        self.goBTN.setFlat(False)
        self.goBTN.setObjectName(_fromUtf8("goBTN"))
        self.versionsGroupBox = QtGui.QGroupBox(SubiTMainForm)
        self.versionsGroupBox.setGeometry(QtCore.QRect(360, 0, 341, 381))
        self.versionsGroupBox.setTitle(QtGui.QApplication.translate("SubiTMainForm", " Versions ", None, QtGui.QApplication.UnicodeUTF8))
        self.versionsGroupBox.setObjectName(_fromUtf8("versionsGroupBox"))
        self.listWidget_2 = QtGui.QListWidget(self.versionsGroupBox)
        self.listWidget_2.setGeometry(QtCore.QRect(10, 20, 321, 351))
        self.listWidget_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.listWidget_2.setObjectName(_fromUtf8("listWidget_2"))
        self.settingsBTN = QtGui.QCommandLinkButton(SubiTMainForm)
        self.settingsBTN.setGeometry(QtCore.QRect(10, 335, 111, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setItalic(False)
        font.setKerning(True)
        self.settingsBTN.setFont(font)
        self.settingsBTN.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.settingsBTN.setAutoFillBackground(False)
        self.settingsBTN.setText(QtGui.QApplication.translate("SubiTMainForm", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("icon-config.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.settingsBTN.setIcon(icon2)
        self.settingsBTN.setIconSize(QtCore.QSize(32, 32))
        self.settingsBTN.setCheckable(False)
        self.settingsBTN.setAutoRepeat(False)
        self.settingsBTN.setObjectName(_fromUtf8("settingsBTN"))
        self.aboutBTN = QtGui.QCommandLinkButton(SubiTMainForm)
        self.aboutBTN.setGeometry(QtCore.QRect(130, 335, 111, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setItalic(False)
        font.setKerning(True)
        self.aboutBTN.setFont(font)
        self.aboutBTN.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.aboutBTN.setAutoFillBackground(False)
        self.aboutBTN.setText(QtGui.QApplication.translate("SubiTMainForm", "About", None, QtGui.QApplication.UnicodeUTF8))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("icon-about.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.aboutBTN.setIcon(icon3)
        self.aboutBTN.setIconSize(QtCore.QSize(32, 32))
        self.aboutBTN.setCheckable(False)
        self.aboutBTN.setAutoRepeat(False)
        self.aboutBTN.setObjectName(_fromUtf8("aboutBTN"))

        self.retranslateUi(SubiTMainForm)
        QtCore.QMetaObject.connectSlotsByName(SubiTMainForm)

    def retranslateUi(self, SubiTMainForm):
        pass

