# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:/dev/SubiT/2.1.0/resources/gui\SubiTMainUi.ui'
#
# Created: Sun Oct 07 14:39:55 2012
#      by: pyside-uic 0.2.14 running on PySide 1.1.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_SubiTMainWindow(object):
    def setupUi(self, SubiTMainWindow):
        SubiTMainWindow.setObjectName("SubiTMainWindow")
        SubiTMainWindow.resize(582, 322)
        SubiTMainWindow.setSizeIncrement(QtCore.QSize(1, 1))
        SubiTMainWindow.setBaseSize(QtCore.QSize(1, 1))
        SubiTMainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        SubiTMainWindow.setAcceptDrops(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Global/icon-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SubiTMainWindow.setWindowIcon(icon)
        SubiTMainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        SubiTMainWindow.setAutoFillBackground(True)
        SubiTMainWindow.setIconSize(QtCore.QSize(128, 128))
        SubiTMainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        SubiTMainWindow.setAnimated(True)
        SubiTMainWindow.setDocumentMode(False)
        SubiTMainWindow.setTabShape(QtGui.QTabWidget.Rounded)
        SubiTMainWindow.setDockNestingEnabled(True)
        SubiTMainWindow.setDockOptions(QtGui.QMainWindow.AllowNestedDocks|QtGui.QMainWindow.AnimatedDocks)
        SubiTMainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.mainWidget = QtGui.QWidget(SubiTMainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainWidget.sizePolicy().hasHeightForWidth())
        self.mainWidget.setSizePolicy(sizePolicy)
        self.mainWidget.setObjectName("mainWidget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.mainWidget)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.inputGroupBox = QtGui.QGroupBox(self.mainWidget)
        self.inputGroupBox.setTitle("")
        self.inputGroupBox.setFlat(False)
        self.inputGroupBox.setObjectName("inputGroupBox")
        self.horizontalLayout = QtGui.QHBoxLayout(self.inputGroupBox)
        self.horizontalLayout.setSpacing(1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.movieNameLabel = QtGui.QLabel(self.inputGroupBox)
        self.movieNameLabel.setEnabled(True)
        self.movieNameLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.movieNameLabel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.movieNameLabel.setStyleSheet("padding-right: 2px")
        self.movieNameLabel.setObjectName("movieNameLabel")
        self.horizontalLayout.addWidget(self.movieNameLabel)
        self.movieNameLineEdit = QtGui.QLineEdit(self.inputGroupBox)
        self.movieNameLineEdit.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.movieNameLineEdit.sizePolicy().hasHeightForWidth())
        self.movieNameLineEdit.setSizePolicy(sizePolicy)
        self.movieNameLineEdit.setMinimumSize(QtCore.QSize(50, 28))
        self.movieNameLineEdit.setMaximumSize(QtCore.QSize(16777215, 28))
        self.movieNameLineEdit.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.movieNameLineEdit.setFont(font)
        self.movieNameLineEdit.setAutoFillBackground(False)
        self.movieNameLineEdit.setStyleSheet("margin-left: 0px;\n"
"margin-right: 0px;")
        self.movieNameLineEdit.setFrame(True)
        self.movieNameLineEdit.setDragEnabled(True)
        self.movieNameLineEdit.setObjectName("movieNameLineEdit")
        self.horizontalLayout.addWidget(self.movieNameLineEdit)
        self.movieNameGoToolButton = QtGui.QToolButton(self.inputGroupBox)
        self.movieNameGoToolButton.setEnabled(False)
        self.movieNameGoToolButton.setMinimumSize(QtCore.QSize(75, 30))
        self.movieNameGoToolButton.setMaximumSize(QtCore.QSize(2, 30))
        self.movieNameGoToolButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.movieNameGoToolButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/MainWindow/icon-main-search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.movieNameGoToolButton.setIcon(icon1)
        self.movieNameGoToolButton.setIconSize(QtCore.QSize(22, 22))
        self.movieNameGoToolButton.setAutoExclusive(False)
        self.movieNameGoToolButton.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.movieNameGoToolButton.setObjectName("movieNameGoToolButton")
        self.horizontalLayout.addWidget(self.movieNameGoToolButton)
        self.movieNameBrowseToolButton = QtGui.QToolButton(self.inputGroupBox)
        self.movieNameBrowseToolButton.setEnabled(False)
        self.movieNameBrowseToolButton.setMinimumSize(QtCore.QSize(30, 30))
        self.movieNameBrowseToolButton.setMaximumSize(QtCore.QSize(30, 30))
        self.movieNameBrowseToolButton.setIconSize(QtCore.QSize(20, 20))
        self.movieNameBrowseToolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.movieNameBrowseToolButton.setObjectName("movieNameBrowseToolButton")
        self.horizontalLayout.addWidget(self.movieNameBrowseToolButton)
        self.verticalLayout_2.addWidget(self.inputGroupBox)
        self.selectionScopeLayout = QtGui.QGridLayout()
        self.selectionScopeLayout.setObjectName("selectionScopeLayout")
        self.listWidgetsLayout = QtGui.QHBoxLayout()
        self.listWidgetsLayout.setObjectName("listWidgetsLayout")
        self.moviesGroupBox = QtGui.QGroupBox(self.mainWidget)
        self.moviesGroupBox.setFlat(False)
        self.moviesGroupBox.setObjectName("moviesGroupBox")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.moviesGroupBox)
        self.horizontalLayout_3.setSpacing(5)
        self.horizontalLayout_3.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.moviesListWidget = QtGui.QListWidget(self.moviesGroupBox)
        self.moviesListWidget.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.moviesListWidget.sizePolicy().hasHeightForWidth())
        self.moviesListWidget.setSizePolicy(sizePolicy)
        self.moviesListWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.moviesListWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.moviesListWidget.setAutoScroll(False)
        self.moviesListWidget.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.moviesListWidget.setProperty("showDropIndicator", False)
        self.moviesListWidget.setAlternatingRowColors(False)
        self.moviesListWidget.setIconSize(QtCore.QSize(16, 16))
        self.moviesListWidget.setObjectName("moviesListWidget")
        self.horizontalLayout_3.addWidget(self.moviesListWidget)
        self.listWidgetsLayout.addWidget(self.moviesGroupBox)
        self.versionsGroupBox = QtGui.QGroupBox(self.mainWidget)
        self.versionsGroupBox.setFlat(False)
        self.versionsGroupBox.setObjectName("versionsGroupBox")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.versionsGroupBox)
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.versionsListWidget = QtGui.QListWidget(self.versionsGroupBox)
        self.versionsListWidget.setEnabled(False)
        self.versionsListWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.versionsListWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.versionsListWidget.setAutoScroll(False)
        self.versionsListWidget.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.versionsListWidget.setProperty("showDropIndicator", False)
        self.versionsListWidget.setObjectName("versionsListWidget")
        self.horizontalLayout_2.addWidget(self.versionsListWidget)
        self.listWidgetsLayout.addWidget(self.versionsGroupBox)
        self.selectionScopeLayout.addLayout(self.listWidgetsLayout, 0, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.selectionScopeLayout)
        self.bottomLayout = QtGui.QHBoxLayout()
        self.bottomLayout.setSpacing(1)
        self.bottomLayout.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.bottomLayout.setContentsMargins(0, -1, -1, -1)
        self.bottomLayout.setObjectName("bottomLayout")
        self.directionLogsFrame = QtGui.QFrame(self.mainWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.directionLogsFrame.sizePolicy().hasHeightForWidth())
        self.directionLogsFrame.setSizePolicy(sizePolicy)
        self.directionLogsFrame.setMinimumSize(QtCore.QSize(0, 30))
        self.directionLogsFrame.setMaximumSize(QtCore.QSize(16777215, 30))
        self.directionLogsFrame.setAutoFillBackground(False)
        self.directionLogsFrame.setStyleSheet("padding: 0px;\n"
"margin: 0px;")
        self.directionLogsFrame.setObjectName("directionLogsFrame")
        self.directionLogsLayout = QtGui.QHBoxLayout(self.directionLogsFrame)
        self.directionLogsLayout.setSpacing(2)
        self.directionLogsLayout.setContentsMargins(0, 1, 0, 1)
        self.directionLogsLayout.setObjectName("directionLogsLayout")
        self.directionLogsIconLabel = QtGui.QLabel(self.directionLogsFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.directionLogsIconLabel.sizePolicy().hasHeightForWidth())
        self.directionLogsIconLabel.setSizePolicy(sizePolicy)
        self.directionLogsIconLabel.setMinimumSize(QtCore.QSize(28, 28))
        self.directionLogsIconLabel.setMaximumSize(QtCore.QSize(28, 28))
        self.directionLogsIconLabel.setStyleSheet("padding: 0px;\n"
"padding-left: 4px;")
        self.directionLogsIconLabel.setText("")
        self.directionLogsIconLabel.setTextFormat(QtCore.Qt.RichText)
        self.directionLogsIconLabel.setPixmap(QtGui.QPixmap(":/MainWindow/icon-main-info.png"))
        self.directionLogsIconLabel.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.directionLogsIconLabel.setObjectName("directionLogsIconLabel")
        self.directionLogsLayout.addWidget(self.directionLogsIconLabel)
        self.directionLogsLabel = QtGui.QLabel(self.directionLogsFrame)
        self.directionLogsLabel.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.directionLogsLabel.sizePolicy().hasHeightForWidth())
        self.directionLogsLabel.setSizePolicy(sizePolicy)
        self.directionLogsLabel.setMinimumSize(QtCore.QSize(0, 28))
        self.directionLogsLabel.setMaximumSize(QtCore.QSize(16777215, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.directionLogsLabel.setFont(font)
        self.directionLogsLabel.setStyleSheet("padding: 0px;\n"
"padding-left: 0px;")
        self.directionLogsLabel.setTextFormat(QtCore.Qt.PlainText)
        self.directionLogsLabel.setScaledContents(False)
        self.directionLogsLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.directionLogsLabel.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.directionLogsLabel.setObjectName("directionLogsLabel")
        self.directionLogsLayout.addWidget(self.directionLogsLabel)
        self.bottomLayout.addWidget(self.directionLogsFrame)
        self.downloadVersionToolButton = QtGui.QToolButton(self.mainWidget)
        self.downloadVersionToolButton.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.downloadVersionToolButton.sizePolicy().hasHeightForWidth())
        self.downloadVersionToolButton.setSizePolicy(sizePolicy)
        self.downloadVersionToolButton.setMinimumSize(QtCore.QSize(95, 30))
        self.downloadVersionToolButton.setMaximumSize(QtCore.QSize(95, 30))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/MainWindow/icon-main-download.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.downloadVersionToolButton.setIcon(icon2)
        self.downloadVersionToolButton.setIconSize(QtCore.QSize(22, 22))
        self.downloadVersionToolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.downloadVersionToolButton.setObjectName("downloadVersionToolButton")
        self.bottomLayout.addWidget(self.downloadVersionToolButton)
        self.toolsToolButton = QtGui.QToolButton(self.mainWidget)
        self.toolsToolButton.setMinimumSize(QtCore.QSize(30, 30))
        self.toolsToolButton.setMaximumSize(QtCore.QSize(30, 30))
        self.toolsToolButton.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.toolsToolButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/MainWindow/icon-main-tools.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolsToolButton.setIcon(icon3)
        self.toolsToolButton.setIconSize(QtCore.QSize(22, 22))
        self.toolsToolButton.setObjectName("toolsToolButton")
        self.bottomLayout.addWidget(self.toolsToolButton)
        self.verticalLayout_2.addLayout(self.bottomLayout)
        SubiTMainWindow.setCentralWidget(self.mainWidget)
        self.logDockWidget = QtGui.QDockWidget(SubiTMainWindow)
        self.logDockWidget.setMinimumSize(QtCore.QSize(91, 113))
        self.logDockWidget.setStyleSheet("")
        self.logDockWidget.setFloating(False)
        self.logDockWidget.setFeatures(QtGui.QDockWidget.NoDockWidgetFeatures)
        self.logDockWidget.setAllowedAreas(QtCore.Qt.BottomDockWidgetArea)
        self.logDockWidget.setObjectName("logDockWidget")
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.logListWidget = QtGui.QListWidget(self.dockWidgetContents)
        self.logListWidget.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logListWidget.sizePolicy().hasHeightForWidth())
        self.logListWidget.setSizePolicy(sizePolicy)
        self.logListWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.logListWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.logListWidget.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.logListWidget.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.logListWidget.setObjectName("logListWidget")
        self.verticalLayout.addWidget(self.logListWidget)
        self.logDockWidget.setWidget(self.dockWidgetContents)
        SubiTMainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.logDockWidget)
        self.actionSubiT_Website = QtGui.QAction(SubiTMainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/icon-global.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSubiT_Website.setIcon(icon4)
        self.actionSubiT_Website.setObjectName("actionSubiT_Website")
        self.actionAbout_SubiT = QtGui.QAction(SubiTMainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/images/icon-about.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout_SubiT.setIcon(icon5)
        self.actionAbout_SubiT.setObjectName("actionAbout_SubiT")
        self.actionBrowse = QtGui.QAction(SubiTMainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/images/icon-search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBrowse.setIcon(icon6)
        self.actionBrowse.setObjectName("actionBrowse")
        self.actionExit = QtGui.QAction(SubiTMainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionShow_Settings = QtGui.QAction(SubiTMainWindow)
        self.actionShow_Settings.setIcon(icon4)
        self.actionShow_Settings.setObjectName("actionShow_Settings")
        self.actionProviders = QtGui.QAction(SubiTMainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/images/icon-handlers.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionProviders.setIcon(icon7)
        self.actionProviders.setObjectName("actionProviders")
        self.actionAssociation = QtGui.QAction(SubiTMainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/images/icon-registry.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAssociation.setIcon(icon8)
        self.actionAssociation.setObjectName("actionAssociation")
        self.movieNameBrowseAction = QtGui.QAction(SubiTMainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/images/icon-browse.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.movieNameBrowseAction.setIcon(icon9)
        self.movieNameBrowseAction.setObjectName("movieNameBrowseAction")
        self.exitAction = QtGui.QAction(SubiTMainWindow)
        self.exitAction.setCheckable(False)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/images/icon-exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exitAction.setIcon(icon10)
        self.exitAction.setObjectName("exitAction")
        self.actionPreferences = QtGui.QAction(SubiTMainWindow)
        self.actionPreferences.setObjectName("actionPreferences")
        self.subitWebsiteAction = QtGui.QAction(SubiTMainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/images/icon-website.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.subitWebsiteAction.setIcon(icon11)
        self.subitWebsiteAction.setObjectName("subitWebsiteAction")
        self.aboutSubitAction = QtGui.QAction(SubiTMainWindow)
        self.aboutSubitAction.setIcon(icon5)
        self.aboutSubitAction.setObjectName("aboutSubitAction")
        self.actionProviders_2 = QtGui.QAction(SubiTMainWindow)
        self.actionProviders_2.setObjectName("actionProviders_2")
        self.actionAssociation_2 = QtGui.QAction(SubiTMainWindow)
        self.actionAssociation_2.setObjectName("actionAssociation_2")
        self.showLogAction = QtGui.QAction(SubiTMainWindow)
        self.showLogAction.setCheckable(True)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/images/icon-log.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.showLogAction.setIcon(icon12)
        self.showLogAction.setShortcutContext(QtCore.Qt.WindowShortcut)
        self.showLogAction.setVisible(True)
        self.showLogAction.setSoftKeyRole(QtGui.QAction.NoSoftKey)
        self.showLogAction.setObjectName("showLogAction")
        self.globalSettingsAction = QtGui.QAction(SubiTMainWindow)
        self.globalSettingsAction.setIcon(icon4)
        self.globalSettingsAction.setObjectName("globalSettingsAction")
        self.providersSettingsAction = QtGui.QAction(SubiTMainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/images/icon-providers.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.providersSettingsAction.setIcon(icon13)
        self.providersSettingsAction.setObjectName("providersSettingsAction")
        self.associationSettingsAction = QtGui.QAction(SubiTMainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/images/icon-association.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.associationSettingsAction.setIcon(icon14)
        self.associationSettingsAction.setObjectName("associationSettingsAction")
        self.prefrencesAction = QtGui.QAction(SubiTMainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/images/icon-config.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.prefrencesAction.setIcon(icon15)
        self.prefrencesAction.setObjectName("prefrencesAction")

        self.retranslateUi(SubiTMainWindow)
        QtCore.QMetaObject.connectSlotsByName(SubiTMainWindow)

    def retranslateUi(self, SubiTMainWindow):
        SubiTMainWindow.setWindowTitle(QtGui.QApplication.translate("SubiTMainWindow", "SubiT", None, QtGui.QApplication.UnicodeUTF8))
        self.movieNameLabel.setText(QtGui.QApplication.translate("SubiTMainWindow", "Movie name:", None, QtGui.QApplication.UnicodeUTF8))
        self.movieNameLineEdit.setPlaceholderText(QtGui.QApplication.translate("SubiTMainWindow", "Drag or Enter movie", None, QtGui.QApplication.UnicodeUTF8))
        self.movieNameBrowseToolButton.setText(QtGui.QApplication.translate("SubiTMainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.moviesGroupBox.setTitle(QtGui.QApplication.translate("SubiTMainWindow", "Movies", None, QtGui.QApplication.UnicodeUTF8))
        self.versionsGroupBox.setTitle(QtGui.QApplication.translate("SubiTMainWindow", "Versions", None, QtGui.QApplication.UnicodeUTF8))
        self.directionLogsLabel.setText(QtGui.QApplication.translate("SubiTMainWindow", "Please wait", None, QtGui.QApplication.UnicodeUTF8))
        self.downloadVersionToolButton.setText(QtGui.QApplication.translate("SubiTMainWindow", "Download", None, QtGui.QApplication.UnicodeUTF8))
        self.logDockWidget.setWindowTitle(QtGui.QApplication.translate("SubiTMainWindow", "Log", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSubiT_Website.setText(QtGui.QApplication.translate("SubiTMainWindow", "SubiT Website", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout_SubiT.setText(QtGui.QApplication.translate("SubiTMainWindow", "About SubiT", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBrowse.setText(QtGui.QApplication.translate("SubiTMainWindow", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("SubiTMainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShow_Settings.setText(QtGui.QApplication.translate("SubiTMainWindow", "Global", None, QtGui.QApplication.UnicodeUTF8))
        self.actionProviders.setText(QtGui.QApplication.translate("SubiTMainWindow", "Providers", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAssociation.setText(QtGui.QApplication.translate("SubiTMainWindow", "Association", None, QtGui.QApplication.UnicodeUTF8))
        self.movieNameBrowseAction.setText(QtGui.QApplication.translate("SubiTMainWindow", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.exitAction.setText(QtGui.QApplication.translate("SubiTMainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPreferences.setText(QtGui.QApplication.translate("SubiTMainWindow", "Global", None, QtGui.QApplication.UnicodeUTF8))
        self.subitWebsiteAction.setText(QtGui.QApplication.translate("SubiTMainWindow", "SubiT\'s Website", None, QtGui.QApplication.UnicodeUTF8))
        self.aboutSubitAction.setText(QtGui.QApplication.translate("SubiTMainWindow", "About SubiT", None, QtGui.QApplication.UnicodeUTF8))
        self.actionProviders_2.setText(QtGui.QApplication.translate("SubiTMainWindow", "Providers", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAssociation_2.setText(QtGui.QApplication.translate("SubiTMainWindow", "Association", None, QtGui.QApplication.UnicodeUTF8))
        self.showLogAction.setText(QtGui.QApplication.translate("SubiTMainWindow", "Show Log", None, QtGui.QApplication.UnicodeUTF8))
        self.globalSettingsAction.setText(QtGui.QApplication.translate("SubiTMainWindow", "Global", None, QtGui.QApplication.UnicodeUTF8))
        self.providersSettingsAction.setText(QtGui.QApplication.translate("SubiTMainWindow", "Providers", None, QtGui.QApplication.UnicodeUTF8))
        self.associationSettingsAction.setText(QtGui.QApplication.translate("SubiTMainWindow", "Association", None, QtGui.QApplication.UnicodeUTF8))
        self.prefrencesAction.setText(QtGui.QApplication.translate("SubiTMainWindow", "Prefrences", None, QtGui.QApplication.UnicodeUTF8))

from Interaction import ImagesResources
