# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\dev\SubiT\resources\gui\SubiTAboutUi_2.0.0.ui'
#
# Created: Wed Jul 25 22:54:19 2012
#      by: pyside-uic 0.2.14 running on PySide 1.1.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_AboutBoxDialog(object):
    def setupUi(self, AboutBoxDialog):
        AboutBoxDialog.setObjectName("AboutBoxDialog")
        AboutBoxDialog.resize(485, 230)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AboutBoxDialog.sizePolicy().hasHeightForWidth())
        AboutBoxDialog.setSizePolicy(sizePolicy)
        AboutBoxDialog.setMinimumSize(QtCore.QSize(485, 230))
        AboutBoxDialog.setMaximumSize(QtCore.QSize(485, 230))
        AboutBoxDialog.setSizeIncrement(QtCore.QSize(0, 0))
        AboutBoxDialog.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Global/icon-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AboutBoxDialog.setWindowIcon(icon)
        AboutBoxDialog.setStyleSheet("")
        AboutBoxDialog.setSizeGripEnabled(False)
        AboutBoxDialog.setModal(False)
        self.verticalLayout = QtGui.QVBoxLayout(AboutBoxDialog)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.TopFrame = QtGui.QFrame(AboutBoxDialog)
        self.TopFrame.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TopFrame.sizePolicy().hasHeightForWidth())
        self.TopFrame.setSizePolicy(sizePolicy)
        self.TopFrame.setMinimumSize(QtCore.QSize(0, 115))
        self.TopFrame.setMaximumSize(QtCore.QSize(16777215, 115))
        self.TopFrame.setAutoFillBackground(False)
        self.TopFrame.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"padding-left: -2px;\n"
"padding-right: -2px;")
        self.TopFrame.setFrameShape(QtGui.QFrame.Panel)
        self.TopFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.TopFrame.setLineWidth(1)
        self.TopFrame.setObjectName("TopFrame")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.TopFrame)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.subitImageLabel = QtGui.QLabel(self.TopFrame)
        self.subitImageLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.subitImageLabel.setMaximumSize(QtCore.QSize(1500, 115))
        self.subitImageLabel.setStyleSheet("padding-top: -20px;")
        self.subitImageLabel.setTextFormat(QtCore.Qt.RichText)
        self.subitImageLabel.setScaledContents(False)
        self.subitImageLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.subitImageLabel.setWordWrap(False)
        self.subitImageLabel.setObjectName("subitImageLabel")
        self.horizontalLayout_2.addWidget(self.subitImageLabel)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.nameLabel = QtGui.QLabel(self.TopFrame)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.nameLabel.setFont(font)
        self.nameLabel.setStyleSheet("padding-left: 2px;")
        self.nameLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.nameLabel.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.nameLabel.setObjectName("nameLabel")
        self.verticalLayout_2.addWidget(self.nameLabel)
        self.versionLabel = QtGui.QLabel(self.TopFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.versionLabel.setFont(font)
        self.versionLabel.setStyleSheet("padding-left: 2px;")
        self.versionLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.versionLabel.setObjectName("versionLabel")
        self.verticalLayout_2.addWidget(self.versionLabel)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 8)
        self.verticalLayout.addWidget(self.TopFrame)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setSpacing(5)
        self.verticalLayout_3.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout_3.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.aboutLabel = QtGui.QLabel(AboutBoxDialog)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.aboutLabel.setFont(font)
        self.aboutLabel.setScaledContents(False)
        self.aboutLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.aboutLabel.setWordWrap(True)
        self.aboutLabel.setOpenExternalLinks(True)
        self.aboutLabel.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse)
        self.aboutLabel.setObjectName("aboutLabel")
        self.verticalLayout_3.addWidget(self.aboutLabel)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.versionStatusLayout = QtGui.QHBoxLayout()
        self.versionStatusLayout.setObjectName("versionStatusLayout")
        self.versionStatusIconLabel = QtGui.QLabel(AboutBoxDialog)
        self.versionStatusIconLabel.setPixmap(QtGui.QPixmap(":/Update/icon-update-latest.png"))
        self.versionStatusIconLabel.setObjectName("versionStatusIconLabel")
        self.versionStatusLayout.addWidget(self.versionStatusIconLabel)
        self.versionStatusTextLabel = QtGui.QLabel(AboutBoxDialog)
        self.versionStatusTextLabel.setEnabled(False)
        self.versionStatusTextLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.versionStatusTextLabel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.versionStatusTextLabel.setTextFormat(QtCore.Qt.PlainText)
        self.versionStatusTextLabel.setScaledContents(True)
        self.versionStatusTextLabel.setWordWrap(False)
        self.versionStatusTextLabel.setObjectName("versionStatusTextLabel")
        self.versionStatusLayout.addWidget(self.versionStatusTextLabel)
        self.versionStatusLayout.setStretch(0, 1)
        self.versionStatusLayout.setStretch(1, 20)
        self.horizontalLayout.addLayout(self.versionStatusLayout)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.closePushButton = QtGui.QPushButton(AboutBoxDialog)
        self.closePushButton.setObjectName("closePushButton")
        self.horizontalLayout.addWidget(self.closePushButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.aboutLabel.setBuddy(self.TopFrame)

        self.retranslateUi(AboutBoxDialog)
        QtCore.QObject.connect(self.closePushButton, QtCore.SIGNAL("clicked()"), AboutBoxDialog.close)
        QtCore.QMetaObject.connectSlotsByName(AboutBoxDialog)

    def retranslateUi(self, AboutBoxDialog):
        AboutBoxDialog.setWindowTitle(QtGui.QApplication.translate("AboutBoxDialog", "About SubiT", None, QtGui.QApplication.UnicodeUTF8))
        self.subitImageLabel.setText(QtGui.QApplication.translate("AboutBoxDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/Global/icon-logo.png\" /></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.nameLabel.setText(QtGui.QApplication.translate("AboutBoxDialog", "<html><head/><body><p><span style=\" font-size:18pt;\">SubiT</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.versionLabel.setText(QtGui.QApplication.translate("AboutBoxDialog", "2.0.0b", None, QtGui.QApplication.UnicodeUTF8))
        self.aboutLabel.setText(QtGui.QApplication.translate("AboutBoxDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">SubiT is an automated system for subtitle downloading. It was created in order to ease the process of downloading subtitles - with just one click you can download subtitles for a whole collection of your favorite movies and TV shows.</p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">SubiT\'s <a href=\"http://subit-app.sourceforge.net/\"><span style=\" text-decoration: underline; color:#0000ff;\">Website</span></a></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.versionStatusTextLabel.setText(QtGui.QApplication.translate("AboutBoxDialog", "SubiT is up to date (2.0.0)", None, QtGui.QApplication.UnicodeUTF8))
        self.closePushButton.setText(QtGui.QApplication.translate("AboutBoxDialog", "Close", None, QtGui.QApplication.UnicodeUTF8))

from Interaction import ImagesResources
