# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:/dev/SubiT/2.1.0/resources/gui\SubiTSettingsUi.ui'
#
# Created: Sun Oct 07 14:39:55 2012
#      by: pyside-uic 0.2.14 running on PySide 1.1.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_SettingsQDialog(object):
    def setupUi(self, SettingsQDialog):
        SettingsQDialog.setObjectName("SettingsQDialog")
        SettingsQDialog.setWindowModality(QtCore.Qt.NonModal)
        SettingsQDialog.setEnabled(True)
        SettingsQDialog.resize(380, 395)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SettingsQDialog.sizePolicy().hasHeightForWidth())
        SettingsQDialog.setSizePolicy(sizePolicy)
        SettingsQDialog.setMinimumSize(QtCore.QSize(380, 395))
        SettingsQDialog.setMaximumSize(QtCore.QSize(380, 395))
        SettingsQDialog.setSizeIncrement(QtCore.QSize(1, 1))
        SettingsQDialog.setBaseSize(QtCore.QSize(380, 380))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Global/icon-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SettingsQDialog.setWindowIcon(icon)
        SettingsQDialog.setLayoutDirection(QtCore.Qt.LeftToRight)
        SettingsQDialog.setSizeGripEnabled(False)
        self.gridLayout_6 = QtGui.QGridLayout(SettingsQDialog)
        self.gridLayout_6.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout_6.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.settingsTabWidget = QtGui.QTabWidget(SettingsQDialog)
        self.settingsTabWidget.setMaximumSize(QtCore.QSize(16777213, 16777215))
        self.settingsTabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.settingsTabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.settingsTabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.settingsTabWidget.setIconSize(QtCore.QSize(24, 24))
        self.settingsTabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.settingsTabWidget.setUsesScrollButtons(False)
        self.settingsTabWidget.setDocumentMode(True)
        self.settingsTabWidget.setTabsClosable(False)
        self.settingsTabWidget.setMovable(False)
        self.settingsTabWidget.setObjectName("settingsTabWidget")
        self.globalTab = QtGui.QWidget()
        self.globalTab.setObjectName("globalTab")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.globalTab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.generalGroupBox = QtGui.QGroupBox(self.globalTab)
        self.generalGroupBox.setFlat(False)
        self.generalGroupBox.setObjectName("generalGroupBox")
        self.verticalLayout = QtGui.QVBoxLayout(self.generalGroupBox)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setContentsMargins(-1, 5, -1, 5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.closeOnFinishCheckBox = QtGui.QCheckBox(self.generalGroupBox)
        self.closeOnFinishCheckBox.setObjectName("closeOnFinishCheckBox")
        self.verticalLayout.addWidget(self.closeOnFinishCheckBox)
        self.defaultDirectoryLabel = QtGui.QLabel(self.generalGroupBox)
        self.defaultDirectoryLabel.setObjectName("defaultDirectoryLabel")
        self.verticalLayout.addWidget(self.defaultDirectoryLabel)
        self.defaultDirectoryLayout = QtGui.QHBoxLayout()
        self.defaultDirectoryLayout.setSpacing(1)
        self.defaultDirectoryLayout.setObjectName("defaultDirectoryLayout")
        self.defaultDirectoryLineEdit = QtGui.QLineEdit(self.generalGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.defaultDirectoryLineEdit.sizePolicy().hasHeightForWidth())
        self.defaultDirectoryLineEdit.setSizePolicy(sizePolicy)
        self.defaultDirectoryLineEdit.setObjectName("defaultDirectoryLineEdit")
        self.defaultDirectoryLayout.addWidget(self.defaultDirectoryLineEdit)
        self.defaultDirectoryBrowseButton = QtGui.QToolButton(self.generalGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.defaultDirectoryBrowseButton.sizePolicy().hasHeightForWidth())
        self.defaultDirectoryBrowseButton.setSizePolicy(sizePolicy)
        self.defaultDirectoryBrowseButton.setObjectName("defaultDirectoryBrowseButton")
        self.defaultDirectoryLayout.addWidget(self.defaultDirectoryBrowseButton)
        self.defaultDirectoryLayout.setStretch(0, 100)
        self.defaultDirectoryLayout.setStretch(1, 1)
        self.verticalLayout.addLayout(self.defaultDirectoryLayout)
        self.alwaysUseDefaultDirCheckBox = QtGui.QCheckBox(self.generalGroupBox)
        self.alwaysUseDefaultDirCheckBox.setObjectName("alwaysUseDefaultDirCheckBox")
        self.verticalLayout.addWidget(self.alwaysUseDefaultDirCheckBox)
        self.verticalLayout_4.addWidget(self.generalGroupBox)
        self.startupGroupBox = QtGui.QGroupBox(self.globalTab)
        self.startupGroupBox.setObjectName("startupGroupBox")
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.startupGroupBox)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.rememberLastWindowSizeCheckBox = QtGui.QCheckBox(self.startupGroupBox)
        self.rememberLastWindowSizeCheckBox.setObjectName("rememberLastWindowSizeCheckBox")
        self.verticalLayout_14.addWidget(self.rememberLastWindowSizeCheckBox)
        self.rememberLastWindowPositionCheckBox = QtGui.QCheckBox(self.startupGroupBox)
        self.rememberLastWindowPositionCheckBox.setObjectName("rememberLastWindowPositionCheckBox")
        self.verticalLayout_14.addWidget(self.rememberLastWindowPositionCheckBox)
        self.verticalLayout_4.addWidget(self.startupGroupBox)
        self.updatesGroupBox = QtGui.QGroupBox(self.globalTab)
        self.updatesGroupBox.setFlat(False)
        self.updatesGroupBox.setObjectName("updatesGroupBox")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.updatesGroupBox)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setContentsMargins(-1, 5, -1, 5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkForUpdatesCheckBox = QtGui.QCheckBox(self.updatesGroupBox)
        self.checkForUpdatesCheckBox.setObjectName("checkForUpdatesCheckBox")
        self.verticalLayout_2.addWidget(self.checkForUpdatesCheckBox)
        self.autoUpdateCheckBox = QtGui.QCheckBox(self.updatesGroupBox)
        self.autoUpdateCheckBox.setObjectName("autoUpdateCheckBox")
        self.verticalLayout_2.addWidget(self.autoUpdateCheckBox)
        self.checkForUpdatesButton = QtGui.QPushButton(self.updatesGroupBox)
        self.checkForUpdatesButton.setAutoDefault(False)
        self.checkForUpdatesButton.setObjectName("checkForUpdatesButton")
        self.verticalLayout_2.addWidget(self.checkForUpdatesButton)
        self.versionStatusLayout = QtGui.QHBoxLayout()
        self.versionStatusLayout.setObjectName("versionStatusLayout")
        self.versionStatusIconLabel = QtGui.QLabel(self.updatesGroupBox)
        self.versionStatusIconLabel.setPixmap(QtGui.QPixmap(":/Update/icon-update-latest.png"))
        self.versionStatusIconLabel.setObjectName("versionStatusIconLabel")
        self.versionStatusLayout.addWidget(self.versionStatusIconLabel)
        self.versionStatusTextLabel = QtGui.QLabel(self.updatesGroupBox)
        self.versionStatusTextLabel.setEnabled(False)
        self.versionStatusTextLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.versionStatusTextLabel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.versionStatusTextLabel.setTextFormat(QtCore.Qt.PlainText)
        self.versionStatusTextLabel.setScaledContents(True)
        self.versionStatusTextLabel.setWordWrap(False)
        self.versionStatusTextLabel.setObjectName("versionStatusTextLabel")
        self.versionStatusLayout.addWidget(self.versionStatusTextLabel)
        self.versionStatusLayout.setStretch(0, 1)
        self.versionStatusLayout.setStretch(1, 20)
        self.verticalLayout_2.addLayout(self.versionStatusLayout)
        self.verticalLayout_4.addWidget(self.updatesGroupBox)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Settings/icon-settings-global.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settingsTabWidget.addTab(self.globalTab, icon1, "")
        self.providersTab = QtGui.QWidget()
        self.providersTab.setObjectName("providersTab")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.providersTab)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.providersGroupBpx = QtGui.QGroupBox(self.providersTab)
        self.providersGroupBpx.setTitle("")
        self.providersGroupBpx.setFlat(False)
        self.providersGroupBpx.setObjectName("providersGroupBpx")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.providersGroupBpx)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label = QtGui.QLabel(self.providersGroupBpx)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setObjectName("label")
        self.verticalLayout_7.addWidget(self.label)
        self.languageOrderLayout = QtGui.QHBoxLayout()
        self.languageOrderLayout.setObjectName("languageOrderLayout")
        self.advancedLanguageListWidget = QtGui.QListWidget(self.providersGroupBpx)
        self.advancedLanguageListWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.advancedLanguageListWidget.setObjectName("advancedLanguageListWidget")
        self.languageOrderLayout.addWidget(self.advancedLanguageListWidget)
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.verticalLayout_12.setContentsMargins(0, 10, 0, 10)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.languageUpToolButton = QtGui.QToolButton(self.providersGroupBpx)
        self.languageUpToolButton.setMinimumSize(QtCore.QSize(50, 0))
        self.languageUpToolButton.setMaximumSize(QtCore.QSize(50, 16777215))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Settings/icon-settings-uparrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.languageUpToolButton.setIcon(icon2)
        self.languageUpToolButton.setArrowType(QtCore.Qt.NoArrow)
        self.languageUpToolButton.setObjectName("languageUpToolButton")
        self.verticalLayout_12.addWidget(self.languageUpToolButton)
        self.languageDownToolButton = QtGui.QToolButton(self.providersGroupBpx)
        self.languageDownToolButton.setMinimumSize(QtCore.QSize(50, 0))
        self.languageDownToolButton.setMaximumSize(QtCore.QSize(50, 16777215))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Settings/icon-settings-downarrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.languageDownToolButton.setIcon(icon3)
        self.languageDownToolButton.setArrowType(QtCore.Qt.NoArrow)
        self.languageDownToolButton.setObjectName("languageDownToolButton")
        self.verticalLayout_12.addWidget(self.languageDownToolButton)
        self.languageOrderLayout.addLayout(self.verticalLayout_12)
        self.verticalLayout_7.addLayout(self.languageOrderLayout)
        self.verticalLayout_3.addLayout(self.verticalLayout_7)
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_2 = QtGui.QLabel(self.providersGroupBpx)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_11.addWidget(self.label_2)
        self.providersOrderLayout = QtGui.QHBoxLayout()
        self.providersOrderLayout.setObjectName("providersOrderLayout")
        self.advancedProvidersListWidget = QtGui.QListWidget(self.providersGroupBpx)
        self.advancedProvidersListWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.advancedProvidersListWidget.setObjectName("advancedProvidersListWidget")
        self.providersOrderLayout.addWidget(self.advancedProvidersListWidget)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.verticalLayout_6.setContentsMargins(0, 10, 0, 10)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.providerUpTooButton = QtGui.QToolButton(self.providersGroupBpx)
        self.providerUpTooButton.setMinimumSize(QtCore.QSize(50, 0))
        self.providerUpTooButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.providerUpTooButton.setIcon(icon2)
        self.providerUpTooButton.setArrowType(QtCore.Qt.NoArrow)
        self.providerUpTooButton.setObjectName("providerUpTooButton")
        self.verticalLayout_6.addWidget(self.providerUpTooButton)
        self.providerDownToolButton = QtGui.QToolButton(self.providersGroupBpx)
        self.providerDownToolButton.setMinimumSize(QtCore.QSize(50, 0))
        self.providerDownToolButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.providerDownToolButton.setIcon(icon3)
        self.providerDownToolButton.setArrowType(QtCore.Qt.NoArrow)
        self.providerDownToolButton.setObjectName("providerDownToolButton")
        self.verticalLayout_6.addWidget(self.providerDownToolButton)
        self.providersOrderLayout.addLayout(self.verticalLayout_6)
        self.verticalLayout_11.addLayout(self.providersOrderLayout)
        self.useAllProvidersCheckBox = QtGui.QCheckBox(self.providersGroupBpx)
        self.useAllProvidersCheckBox.setObjectName("useAllProvidersCheckBox")
        self.verticalLayout_11.addWidget(self.useAllProvidersCheckBox)
        self.verticalLayout_3.addLayout(self.verticalLayout_11)
        self.verticalLayout_5.addWidget(self.providersGroupBpx)
        self.flowGroupBox = QtGui.QGroupBox(self.providersTab)
        self.flowGroupBox.setObjectName("flowGroupBox")
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.flowGroupBox)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.rankUsingPropertiesCheckBox = QtGui.QCheckBox(self.flowGroupBox)
        self.rankUsingPropertiesCheckBox.setObjectName("rankUsingPropertiesCheckBox")
        self.verticalLayout_13.addWidget(self.rankUsingPropertiesCheckBox)
        self.inDepthSearchCheckBox = QtGui.QCheckBox(self.flowGroupBox)
        self.inDepthSearchCheckBox.setObjectName("inDepthSearchCheckBox")
        self.verticalLayout_13.addWidget(self.inDepthSearchCheckBox)
        self.verticalLayout_5.addWidget(self.flowGroupBox)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Settings/icon-settings-providers.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settingsTabWidget.addTab(self.providersTab, icon4, "")
        self.associationTab = QtGui.QWidget()
        self.associationTab.setObjectName("associationTab")
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.associationTab)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.fileExtensionsGroupBpx = QtGui.QGroupBox(self.associationTab)
        self.fileExtensionsGroupBpx.setTitle("")
        self.fileExtensionsGroupBpx.setFlat(False)
        self.fileExtensionsGroupBpx.setObjectName("fileExtensionsGroupBpx")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.fileExtensionsGroupBpx)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.associateExtensionsCheckBox = QtGui.QCheckBox(self.fileExtensionsGroupBpx)
        self.associateExtensionsCheckBox.setChecked(False)
        self.associateExtensionsCheckBox.setObjectName("associateExtensionsCheckBox")
        self.verticalLayout_8.addWidget(self.associateExtensionsCheckBox)
        self.extensionsGroupBox = QtGui.QGroupBox(self.fileExtensionsGroupBpx)
        self.extensionsGroupBox.setEnabled(False)
        self.extensionsGroupBox.setFlat(True)
        self.extensionsGroupBox.setObjectName("extensionsGroupBox")
        self.extensionsWholeLayout = QtGui.QVBoxLayout(self.extensionsGroupBox)
        self.extensionsWholeLayout.setObjectName("extensionsWholeLayout")
        self.extensionsSelectionLabel = QtGui.QLabel(self.extensionsGroupBox)
        self.extensionsSelectionLabel.setObjectName("extensionsSelectionLabel")
        self.extensionsWholeLayout.addWidget(self.extensionsSelectionLabel)
        self.extensionsLayout = QtGui.QHBoxLayout()
        self.extensionsLayout.setSpacing(5)
        self.extensionsLayout.setObjectName("extensionsLayout")
        self.extensionsListWidget = QtGui.QListWidget(self.extensionsGroupBox)
        self.extensionsListWidget.setMinimumSize(QtCore.QSize(0, 80))
        self.extensionsListWidget.setMaximumSize(QtCore.QSize(16777215, 80))
        self.extensionsListWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.extensionsListWidget.setObjectName("extensionsListWidget")
        self.extensionsLayout.addWidget(self.extensionsListWidget)
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setSpacing(1)
        self.verticalLayout_10.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.verticalLayout_10.setContentsMargins(-1, 30, -1, 30)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.extensionsAddToolButton = QtGui.QToolButton(self.extensionsGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.extensionsAddToolButton.sizePolicy().hasHeightForWidth())
        self.extensionsAddToolButton.setSizePolicy(sizePolicy)
        self.extensionsAddToolButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/Settings/icon-settings-add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.extensionsAddToolButton.setIcon(icon5)
        self.extensionsAddToolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.extensionsAddToolButton.setArrowType(QtCore.Qt.NoArrow)
        self.extensionsAddToolButton.setObjectName("extensionsAddToolButton")
        self.verticalLayout_10.addWidget(self.extensionsAddToolButton)
        self.extensionsDeleteToolButton = QtGui.QToolButton(self.extensionsGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.extensionsDeleteToolButton.sizePolicy().hasHeightForWidth())
        self.extensionsDeleteToolButton.setSizePolicy(sizePolicy)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/Settings/icon-settings-remove.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.extensionsDeleteToolButton.setIcon(icon6)
        self.extensionsDeleteToolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.extensionsDeleteToolButton.setArrowType(QtCore.Qt.NoArrow)
        self.extensionsDeleteToolButton.setObjectName("extensionsDeleteToolButton")
        self.verticalLayout_10.addWidget(self.extensionsDeleteToolButton)
        self.extensionsLayout.addLayout(self.verticalLayout_10)
        self.extensionsWholeLayout.addLayout(self.extensionsLayout)
        self.interactionTypeSelectionLabel = QtGui.QLabel(self.extensionsGroupBox)
        self.interactionTypeSelectionLabel.setLineWidth(1)
        self.interactionTypeSelectionLabel.setScaledContents(False)
        self.interactionTypeSelectionLabel.setWordWrap(True)
        self.interactionTypeSelectionLabel.setObjectName("interactionTypeSelectionLabel")
        self.extensionsWholeLayout.addWidget(self.interactionTypeSelectionLabel)
        self.interactionTypeSelectionComboBox = QtGui.QComboBox(self.extensionsGroupBox)
        self.interactionTypeSelectionComboBox.setObjectName("interactionTypeSelectionComboBox")
        self.extensionsWholeLayout.addWidget(self.interactionTypeSelectionComboBox)
        self.verticalLayout_8.addWidget(self.extensionsGroupBox)
        self.verticalLayout_9.addWidget(self.fileExtensionsGroupBpx)
        spacerItem1 = QtGui.QSpacerItem(20, 80, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.verticalLayout_9.addItem(spacerItem1)
        self.verticalLayout_9.setStretch(0, 20)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/Settings/icon-settings-association.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settingsTabWidget.addTab(self.associationTab, icon7, "")
        self.gridLayout_6.addWidget(self.settingsTabWidget, 0, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.okPushButton = QtGui.QPushButton(SettingsQDialog)
        self.okPushButton.setStyleSheet("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/Settings/icon-settings-ok.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.okPushButton.setIcon(icon8)
        self.okPushButton.setIconSize(QtCore.QSize(16, 16))
        self.okPushButton.setObjectName("okPushButton")
        self.horizontalLayout.addWidget(self.okPushButton)
        self.cancelPushButton = QtGui.QPushButton(SettingsQDialog)
        self.cancelPushButton.setStyleSheet("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/Settings/icon-settings-cancel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cancelPushButton.setIcon(icon9)
        self.cancelPushButton.setIconSize(QtCore.QSize(16, 16))
        self.cancelPushButton.setAutoDefault(False)
        self.cancelPushButton.setObjectName("cancelPushButton")
        self.horizontalLayout.addWidget(self.cancelPushButton)
        self.gridLayout_6.addLayout(self.horizontalLayout, 2, 0, 1, 1)

        self.retranslateUi(SettingsQDialog)
        self.settingsTabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.associateExtensionsCheckBox, QtCore.SIGNAL("toggled(bool)"), self.extensionsGroupBox.setEnabled)
        QtCore.QObject.connect(self.checkForUpdatesCheckBox, QtCore.SIGNAL("toggled(bool)"), self.autoUpdateCheckBox.setEnabled)
        QtCore.QObject.connect(self.cancelPushButton, QtCore.SIGNAL("clicked()"), SettingsQDialog.close)
        QtCore.QObject.connect(self.associateExtensionsCheckBox, QtCore.SIGNAL("toggled(bool)"), self.extensionsGroupBox.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(SettingsQDialog)

    def retranslateUi(self, SettingsQDialog):
        SettingsQDialog.setWindowTitle(QtGui.QApplication.translate("SettingsQDialog", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.generalGroupBox.setTitle(QtGui.QApplication.translate("SettingsQDialog", "General", None, QtGui.QApplication.UnicodeUTF8))
        self.closeOnFinishCheckBox.setText(QtGui.QApplication.translate("SettingsQDialog", "Close program on finish", None, QtGui.QApplication.UnicodeUTF8))
        self.defaultDirectoryLabel.setText(QtGui.QApplication.translate("SettingsQDialog", "Default Direcotry:", None, QtGui.QApplication.UnicodeUTF8))
        self.defaultDirectoryBrowseButton.setText(QtGui.QApplication.translate("SettingsQDialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.alwaysUseDefaultDirCheckBox.setText(QtGui.QApplication.translate("SettingsQDialog", "Always use default directory", None, QtGui.QApplication.UnicodeUTF8))
        self.startupGroupBox.setTitle(QtGui.QApplication.translate("SettingsQDialog", "Startup", None, QtGui.QApplication.UnicodeUTF8))
        self.rememberLastWindowSizeCheckBox.setText(QtGui.QApplication.translate("SettingsQDialog", "Remeber last window size", None, QtGui.QApplication.UnicodeUTF8))
        self.rememberLastWindowPositionCheckBox.setText(QtGui.QApplication.translate("SettingsQDialog", "Remeber last window position", None, QtGui.QApplication.UnicodeUTF8))
        self.updatesGroupBox.setTitle(QtGui.QApplication.translate("SettingsQDialog", "Updates", None, QtGui.QApplication.UnicodeUTF8))
        self.checkForUpdatesCheckBox.setText(QtGui.QApplication.translate("SettingsQDialog", "Check for updates", None, QtGui.QApplication.UnicodeUTF8))
        self.autoUpdateCheckBox.setText(QtGui.QApplication.translate("SettingsQDialog", "Auto update", None, QtGui.QApplication.UnicodeUTF8))
        self.checkForUpdatesButton.setText(QtGui.QApplication.translate("SettingsQDialog", "Check For Updates", None, QtGui.QApplication.UnicodeUTF8))
        self.versionStatusTextLabel.setText(QtGui.QApplication.translate("SettingsQDialog", "SubiT is up to date (2.0.0)", None, QtGui.QApplication.UnicodeUTF8))
        self.settingsTabWidget.setTabText(self.settingsTabWidget.indexOf(self.globalTab), QtGui.QApplication.translate("SettingsQDialog", "Global", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("SettingsQDialog", "Langauge Order:", None, QtGui.QApplication.UnicodeUTF8))
        self.languageUpToolButton.setText(QtGui.QApplication.translate("SettingsQDialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.languageDownToolButton.setText(QtGui.QApplication.translate("SettingsQDialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("SettingsQDialog", "Providers Order:", None, QtGui.QApplication.UnicodeUTF8))
        self.providerUpTooButton.setText(QtGui.QApplication.translate("SettingsQDialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.providerDownToolButton.setText(QtGui.QApplication.translate("SettingsQDialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.useAllProvidersCheckBox.setText(QtGui.QApplication.translate("SettingsQDialog", "Use all the avaliable providers", None, QtGui.QApplication.UnicodeUTF8))
        self.flowGroupBox.setTitle(QtGui.QApplication.translate("SettingsQDialog", "Flow", None, QtGui.QApplication.UnicodeUTF8))
        self.rankUsingPropertiesCheckBox.setText(QtGui.QApplication.translate("SettingsQDialog", "Rank using only Resolution and Audio proprerties", None, QtGui.QApplication.UnicodeUTF8))
        self.inDepthSearchCheckBox.setText(QtGui.QApplication.translate("SettingsQDialog", "Perform In Depth search when needed", None, QtGui.QApplication.UnicodeUTF8))
        self.settingsTabWidget.setTabText(self.settingsTabWidget.indexOf(self.providersTab), QtGui.QApplication.translate("SettingsQDialog", "Providers", None, QtGui.QApplication.UnicodeUTF8))
        self.associateExtensionsCheckBox.setText(QtGui.QApplication.translate("SettingsQDialog", "Associate extensions", None, QtGui.QApplication.UnicodeUTF8))
        self.extensionsSelectionLabel.setText(QtGui.QApplication.translate("SettingsQDialog", "Select file extensions for right click menu:", None, QtGui.QApplication.UnicodeUTF8))
        self.extensionsAddToolButton.setText(QtGui.QApplication.translate("SettingsQDialog", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.extensionsDeleteToolButton.setText(QtGui.QApplication.translate("SettingsQDialog", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.interactionTypeSelectionLabel.setText(QtGui.QApplication.translate("SettingsQDialog", "Interaction mode when launching from Context Menu:", None, QtGui.QApplication.UnicodeUTF8))
        self.settingsTabWidget.setTabText(self.settingsTabWidget.indexOf(self.associationTab), QtGui.QApplication.translate("SettingsQDialog", "Context Menu", None, QtGui.QApplication.UnicodeUTF8))
        self.okPushButton.setText(QtGui.QApplication.translate("SettingsQDialog", "OK", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelPushButton.setText(QtGui.QApplication.translate("SettingsQDialog", "Cancel", None, QtGui.QApplication.UnicodeUTF8))

from Interaction import ImagesResources
from Interaction import ImagesResources
